=== christf/navit/navit/navit.dtd
<!ELEMENT config (plugins,debug*,navit)>
<!ATTLIST config xmlns:xi CDATA #REQUIRED>
<!ATTLIST config language CDATA #IMPLIED>
<!ELEMENT plugins (plugin*)>
<!ELEMENT plugin EMPTY>
<!ATTLIST plugin path CDATA #REQUIRED>
<!ATTLIST plugin active CDATA #IMPLIED>
<!ATTLIST plugin ondemand CDATA #IMPLIED>
<!ELEMENT debug EMPTY>
<!ATTLIST debug name CDATA #REQUIRED>
<!ATTLIST debug level CDATA "0">
<!ATTLIST debug dbg_level (error|warning|info|debug) "error">
<!ELEMENT log EMPTY>
<!ATTLIST log enabled CDATA #IMPLIED>
<!ATTLIST log type CDATA #REQUIRED>
<!ATTLIST log data CDATA #REQUIRED>
<!ATTLIST log flush_size CDATA #IMPLIED>
<!ATTLIST log flush_time CDATA #IMPLIED>
<!ATTLIST log attr_types CDATA #IMPLIED>
<!ELEMENT navit (graphics,gui+,log*,osd*,traffic*,vehicle*,tracking?,vehicleprofile*,route,navigation,speech,mapset+,layer+,xi:include+,layout+) >
<!ATTLIST navit center CDATA #REQUIRED>
<!ATTLIST navit zoom CDATA #REQUIRED>
<!ATTLIST navit tracking CDATA #REQUIRED>
<!ATTLIST navit orientation CDATA #REQUIRED>
<!ATTLIST navit recent_dest CDATA #IMPLIED>
<!ATTLIST navit drag_bitmap CDATA #IMPLIED>
<!ATTLIST navit default_layout CDATA #IMPLIED>
<!ATTLIST navit tunnel_nightlayout CDATA #IMPLIED>
<!ATTLIST navit nightlayout_auto CDATA #IMPLIED>
<!ATTLIST navit sunrise_degrees CDATA #IMPLIED>
<!ELEMENT gui ANY>
<!ATTLIST gui type CDATA #REQUIRED>
<!ATTLIST gui menubar CDATA #IMPLIED>
<!ATTLIST gui toolbar CDATA #IMPLIED>
<!ATTLIST gui statusbar CDATA #IMPLIED>
<!ATTLIST gui skin CDATA #IMPLIED>
<!ATTLIST gui fullscreen CDATA #IMPLIED>
<!ATTLIST gui enabled CDATA #IMPLIED>
<!ELEMENT graphics EMPTY>
<!ATTLIST graphics type CDATA #REQUIRED>
<!ATTLIST graphics event_loop_system CDATA #IMPLIED>
<!ELEMENT vehicle (log*)>
<!ATTLIST vehicle name CDATA #REQUIRED>
<!ATTLIST vehicle source CDATA #REQUIRED>
<!ATTLIST vehicle enabled CDATA #IMPLIED>
<!ATTLIST vehicle active CDATA #IMPLIED>
<!ATTLIST vehicle follow CDATA #IMPLIED>
<!ATTLIST vehicle update CDATA #IMPLIED>
<!ATTLIST vehicle gpsd_query CDATA #IMPLIED>
<!ATTLIST vehicle profilename CDATA #IMPLIED>
<!ELEMENT vehicleprofile (roadprofile+)>
<!ATTLIST vehicleprofile name CDATA #REQUIRED>
<!ATTLIST vehicleprofile flags CDATA #REQUIRED>
<!ATTLIST vehicleprofile flags_forward_mask CDATA #REQUIRED>
<!ATTLIST vehicleprofile flags_reverse_mask CDATA #REQUIRED>
<!ATTLIST vehicleprofile route_mode CDATA #REQUIRED>
<!ATTLIST vehicleprofile route_depth CDATA #IMPLIED>
<!ATTLIST vehicleprofile static_distance CDATA #IMPLIED>
<!ATTLIST vehicleprofile static_speed CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_width CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_height CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_length CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_weight CDATA #IMPLIED>
<!ATTLIST vehicleprofile vehicle_axle_weight CDATA #IMPLIED>
<!ELEMENT coord EMPTY>
<!ATTLIST coord x CDATA #REQUIRED>
<!ATTLIST coord y CDATA #REQUIRED>
<!ELEMENT cursor (itemgra+)>
<!ATTLIST cursor w CDATA #REQUIRED>
<!ATTLIST cursor h CDATA #REQUIRED>
<!ELEMENT traffic EMPTY>
<!ATTLIST traffic type CDATA #REQUIRED>
<!ELEMENT tracking ANY>
<!ATTLIST tracking cdf_histsize CDATA #IMPLIED>
<!ELEMENT route EMPTY>
<!ATTLIST route destination_distance CDATA #IMPLIED>
<!ELEMENT roadprofile EMPTY>
<!ATTLIST roadprofile item_types CDATA #REQUIRED>
<!ATTLIST roadprofile speed CDATA #REQUIRED>
<!ATTLIST roadprofile maxspeed CDATA #IMPLIED>
<!ELEMENT speed EMPTY>
<!ATTLIST speed type CDATA #REQUIRED>
<!ATTLIST speed value CDATA #REQUIRED>
<!ELEMENT navigation (announce+)>
<!ELEMENT announce EMPTY>
<!ATTLIST announce type CDATA #REQUIRED>
<!ATTLIST announce level0 CDATA #IMPLIED>
<!ATTLIST announce level1 CDATA #IMPLIED>
<!ATTLIST announce level2 CDATA #IMPLIED>
<!ELEMENT speech EMPTY>
<!ATTLIST speech active CDATA #REQUIRED>
<!ATTLIST speech type CDATA #REQUIRED>
<!ATTLIST speech data CDATA #REQUIRED>
<!ATTLIST speech cps CDATA #IMPLIED>
<!ATTLIST speech vocabulary_name CDATA #IMPLIED>
<!ATTLIST speech vocabulary_name_systematic CDATA #IMPLIED>
<!ATTLIST speech vocabulary_distances CDATA #IMPLIED>
<!ATTLIST speech sample_suffix CDATA #IMPLIED>
<!ATTLIST speech cache_size CDATA #IMPLIED>
<!ATTLIST speech subtype CDATA #IMPLIED>
<!ELEMENT mapset (map*,xi:include*)>
<!ATTLIST mapset enabled CDATA #IMPLIED>
<!ELEMENT map EMPTY>
<!ATTLIST map type CDATA #REQUIRED>
<!ATTLIST map enabled CDATA #IMPLIED>
<!ATTLIST map active CDATA #IMPLIED>
<!ATTLIST map data CDATA #REQUIRED>
<!ATTLIST map debug CDATA #IMPLIED>
<!ELEMENT layout (cursor*,xi:include*,layer+)*>
<!ATTLIST layout name CDATA #REQUIRED>
<!ATTLIST layout active CDATA #IMPLIED>
<!ATTLIST layout color CDATA #IMPLIED>
<!ATTLIST layout font CDATA #IMPLIED>
<!ATTLIST layout daylayout CDATA #IMPLIED>
<!ATTLIST layout nightlayout CDATA #IMPLIED>
<!ATTLIST layout icon_w CDATA #IMPLIED>
<!ATTLIST layout icon_h CDATA #IMPLIED>
<!ATTLIST layout underground_alpha CDATA #IMPLIED>
<!ATTLIST layout xmlns:xi CDATA #IMPLIED>
<!ELEMENT layer (itemgra*)>
<!ATTLIST layer enabled CDATA #IMPLIED>
<!ATTLIST layer name CDATA #IMPLIED>
<!ATTLIST layer details CDATA #IMPLIED>
<!ATTLIST layer order CDATA #IMPLIED>
<!ATTLIST layer ref CDATA #IMPLIED>
<!ATTLIST layer active CDATA #IMPLIED>
<!ELEMENT osd EMPTY>
<!ATTLIST osd enabled CDATA #IMPLIED>
<!ATTLIST osd type CDATA #REQUIRED>
<!ATTLIST osd x CDATA #IMPLIED>
<!ATTLIST osd y CDATA #IMPLIED>
<!ATTLIST osd src CDATA #IMPLIED>
<!ATTLIST osd command CDATA #IMPLIED>
<!ATTLIST osd data CDATA #IMPLIED>
<!ELEMENT itemgra (polygon|polyline|text|circle|icon|image|arrows|spikes)*>
<!ATTLIST itemgra item_types CDATA #IMPLIED>
<!ATTLIST itemgra order CDATA #IMPLIED>
<!ATTLIST itemgra speed_range CDATA #IMPLIED>
<!ELEMENT polygon (coord*)>
<!ATTLIST polygon color CDATA #REQUIRED>
<!ATTLIST polygon oneway CDATA #IMPLIED>
<!ATTLIST polygon src CDATA #IMPLIED>
<!ATTLIST polygon w CDATA #IMPLIED>
<!ATTLIST polygon h CDATA #IMPLIED>
<!ELEMENT polyline (coord*)>
<!ATTLIST polyline color CDATA #REQUIRED>
<!ATTLIST polyline width CDATA #IMPLIED>
<!ATTLIST polyline dash CDATA #IMPLIED>
<!ATTLIST polyline offset CDATA #IMPLIED>
<!ATTLIST polyline radius CDATA #IMPLIED>
<!ATTLIST polyline oneway CDATA #IMPLIED>
<!ELEMENT text EMPTY>
<!ATTLIST text text_size CDATA #REQUIRED>
<!ATTLIST text color CDATA #IMPLIED>
<!ATTLIST text background_color CDATA #IMPLIED>
<!ATTLIST text oneway CDATA #IMPLIED>
<!ELEMENT circle (coord*)>
<!ATTLIST circle color CDATA #REQUIRED>
<!ATTLIST circle radius CDATA #REQUIRED>
<!ATTLIST circle width CDATA #IMPLIED>
<!ATTLIST circle text_size CDATA #IMPLIED>
<!ATTLIST circle background_color CDATA #IMPLIED>
<!ATTLIST circle oneway CDATA #IMPLIED>
<!ELEMENT icon EMPTY>
<!ATTLIST icon src CDATA #REQUIRED>
<!ATTLIST icon w CDATA #IMPLIED>
<!ATTLIST icon h CDATA #IMPLIED>
<!ATTLIST icon x CDATA #IMPLIED>
<!ATTLIST icon y CDATA #IMPLIED>
<!ELEMENT arrows EMPTY>
<!ATTLIST arrows color CDATA #REQUIRED>
<!ATTLIST arrows width CDATA #IMPLIED>
<!ATTLIST arrows oneway CDATA #IMPLIED>
<!ELEMENT spikes EMPTY>
<!ATTLIST spikes color CDATA #REQUIRED>
<!ATTLIST spikes width CDATA #IMPLIED>
<!ATTLIST spikes distance CDATA #IMPLIED>
<!ELEMENT image EMPTY>
<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include href CDATA #IMPLIED>
<!ATTLIST xi:include xpointer CDATA #IMPLIED>

=== christf/navit/navit/tests/gtkglarea/speedwarner_navit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "navit.dtd">
<config xmlns:xi="http://www.w3.org/2001/XInclude">
	<plugins>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}lib*.so" ondemand="no"/>
		<plugin path="$NAVIT_LIBDIR/autoload/${NAVIT_LIBPREFIX}lib*.so"/>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}libbinding_dbus.so" active="no"/>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}libgraphics_null.so" active="no"/>
	</plugins>

	<navit center="11.613494 52.750079" zoom="256" tracking="1" orientation="-1" drag_bitmap="1">
		<!-- GRAPHICS_TYPE is substituted by the runner script -->
		<graphics type="GRAPHICS_TYPE" w="300" h="300"/>

		<gui type="internal" enabled="yes"><![CDATA[
			<html>
				<img src="gui_map"/>
				<a name='Main Menu'><text>Main menu</text>
					<a href='#Settings'><img src="gui_settings"/><text>Settings</text></a>
				</a>
			</html>
		]]></gui>

		<osd enabled="yes" type="speed_warner" w="46" h="46" x="0" y="0" use_overlay="1"
		     font_size="250" speed_exceed_limit_offset="5" speed_exceed_limit_percent="3"
		     announce_on="0" background_color="#00000000"/>

		<vehicle name="Demo" profilename="car" enabled="yes" active="yes"
		        source="demo://" speed="30" follow="1"/>

		<tracking cdf_histsize="0"/>

		<vehicleprofile name="car" route_depth="18:25%" flags="0x4000000"
		               flags_forward_mask="0x4040002" flags_reverse_mask="0x4040001"
		               route_mode="0" static_speed="5" static_distance="25">
			<roadprofile item_types="street_0,street_1_city,street_2_city,street_3_city" speed="50"/>
			<roadprofile item_types="highway_city,street_1_land,street_2_land" speed="100"/>
			<roadprofile item_types="highway_land,street_n_lanes" speed="120"/>
		</vehicleprofile>

		<route destination_distance="50"/>

		<!-- MAPFILE is substituted by the runner script; navit refuses to start without a mapset -->
		<mapset enabled="yes">
			<map type="binfile" enabled="yes" data="MAPFILE"/>
		</mapset>

		<xi:include href="$NAVIT_SHAREDIR/navit_layout_*.xml"/>
	</navit>
</config>

=== christf/navit/navit/tests/gtkglarea/demo_stall_navit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "navit.dtd">
<config xmlns:xi="http://www.w3.org/2001/XInclude">
	<plugins>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}lib*.so" ondemand="no"/>
		<plugin path="$NAVIT_LIBDIR/autoload/${NAVIT_LIBPREFIX}lib*.so"/>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}libbinding_dbus.so" active="no"/>
		<plugin path="$NAVIT_LIBDIR/*/${NAVIT_LIBPREFIX}libgraphics_null.so" active="no"/>
	</plugins>

	<debug name="vehicle_demo" dbg_level="debug"/>
	<debug name="segv" level="1"/>

	<!-- The user reports the demo vehicle only stalls with follow="1" and
	     orientation="-1" (course up, map rotates). Both are set here on purpose;
	     override NAVIT_ORIENTATION / FOLLOW to check the other combinations. -->
	<navit center="11.614722 52.107222" zoom="-9" tracking="1" orientation="ORIENTATION" drag_bitmap="0">
		<graphics type="GRAPHICS_TYPE" w="800" h="600"/>

		<gui type="internal" enabled="yes"><![CDATA[
			<html>
				<script>
					navit.set_position("SLNG SLAT");
					navit.set_destination("DLNG DLAT", "Lerchenwuhne 20");
				</script>
				<img src="gui_map"/>
			</html>
		]]></gui>

		<vehicle name="Demo" profilename="car" enabled="yes" active="yes"
		        source="demo://" speed="40" follow="FOLLOW"/>

		<tracking cdf_histsize="0"/>

		<vehicleprofile name="car" route_depth="18:25%" flags="0x4000000"
		               flags_forward_mask="0x4040002" flags_reverse_mask="0x4040001"
		               route_mode="0" static_speed="5" static_distance="25">
			<roadprofile item_types="street_0,street_1_city,living_street,street_service,track_gravelled,track_unpaved,street_parking_lane" speed="10"/>
			<roadprofile item_types="street_2_city,track_paved" speed="30"/>
			<roadprofile item_types="street_3_city" speed="40"/>
			<roadprofile item_types="street_4_city,highway_city" speed="60"/>
			<roadprofile item_types="street_1_land" speed="60"/>
			<roadprofile item_types="street_2_land" speed="65"/>
			<roadprofile item_types="street_3_land" speed="70"/>
			<roadprofile item_types="street_4_land,highway_land,street_n_lanes" speed="120"/>
			<roadprofile item_types="ramp,ferry" speed="40"/>
		</vehicleprofile>

		<route destination_distance="50"/>

		<mapset enabled="yes">
			<map type="binfile" enabled="yes" data="/home/christof/nobackup/osm/sachsen-anhalt.bin"/>
		</mapset>

		<xi:include href="$NAVIT_SHAREDIR/navit_layout_*.xml"/>
	</navit>
</config>
